'use client'

import { useState } from 'react'
import { X, Check, Ban, RefreshCw, ExternalLink, MapPin } from 'lucide-react'
import StatusPill from '@/components/ui/StatusPill'
import Button from '@/components/ui/Button'
import Textarea from '@/components/ui/Textarea'
import CopywritingLoader from '@/components/copywriting/CopywritingLoader'
import type { CopywritingResearchEntry } from '@/types'

interface Props {
  open: boolean
  onClose: () => void
  entries: CopywritingResearchEntry[]
  projectId: string
  onChanged: () => Promise<void>
  readOnly?: boolean
  /** Called when a finding is regenerated by Gemini (shows the AI disclaimer). */
  onAiResult?: () => void
  /** Approved findings the current draft doesn't use yet (0 hides the button). */
  applyCount?: number
  /** Closes the ledger and works those findings into the draft via a refine. */
  onApplyApproved?: () => void
}

// The Research Ledger: every Gemini-checked claim, permanently attached to
// the article (FLOW-06). Findings the writer hasn't decided on yet can be
// approved, rejected, or regenerated with feedback right here.
export default function ResearchLedgerModal({ open, onClose, entries, projectId, onChanged, readOnly, onAiResult, applyCount = 0, onApplyApproved }: Props) {
  const [regenOpenId, setRegenOpenId] = useState<string | null>(null)
  const [feedback, setFeedback] = useState('')
  const [busyId, setBusyId] = useState<string | null>(null)
  const [regeneratingId, setRegeneratingId] = useState<string | null>(null)

  if (!open) return null

  async function act(id: string, action: string, extra: Record<string, unknown> = {}) {
    setBusyId(id)
    if (action === 'regenerate') setRegeneratingId(id)
    const res = await fetch(`/api/copywriting/${projectId}/claims/${id}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ action, ...extra }),
    })
    setBusyId(null)
    setRegeneratingId(null)
    await onChanged()
    if (res.ok && action === 'regenerate') onAiResult?.()
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/40" onClick={onClose} />
      <div className="relative bg-white w-full max-w-2xl max-h-[85vh] overflow-y-auto rounded-sm shadow-xl">
        <div className="flex items-center justify-between px-6 py-4 border-b border-[#e5e3df] sticky top-0 bg-white">
          <h3 className="text-sm font-semibold text-gray-900">Research Ledger</h3>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-700">
            <X size={16} />
          </button>
        </div>

        {/* After approving findings, the writer can go straight to working them
            into the draft — runs as a refine in the chat on the draft screen. */}
        {!readOnly && applyCount > 0 && onApplyApproved && (
          <div className="sticky top-[53px] z-10 flex flex-wrap items-center justify-between gap-3 border-b border-emerald-200 bg-emerald-50 px-6 py-3">
            <p className="text-xs text-emerald-900">
              {applyCount} approved finding{applyCount === 1 ? '' : 's'} not in the draft yet
            </p>
            <Button size="sm" onClick={onApplyApproved}>
              Update draft with approved research
            </Button>
          </div>
        )}

        <div className="p-6 flex flex-col gap-4">
          {entries.length === 0 && <p className="text-sm text-gray-400">No research has been run on this article yet.</p>}
          {entries.map((e) => (
            <div key={e.id} className="border border-[#e5e3df] p-4">
              <div className="flex items-start justify-between gap-3">
                <p className="text-sm text-gray-800 leading-relaxed">{e.claim}</p>
                <StatusPill
                  label={e.status}
                  tone={e.status === 'approved' ? 'emerald' : e.status === 'rejected' ? 'red' : 'amber'}
                />
              </div>
              <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-gray-500">
                {e.source_url && (
                  <a href={e.source_url} target="_blank" rel="noreferrer" className="flex items-center gap-1 text-blue-600 hover:underline">
                    <ExternalLink size={11} /> Source
                  </a>
                )}
                {e.publication_date && <span>Published: {e.publication_date}</span>}
                {e.period_covered && <span>Period: {e.period_covered}</span>}
                {e.confidence && <span>Confidence: {e.confidence}</span>}
              </div>
              {e.caveats && <p className="mt-1.5 text-xs text-amber-700">Caveat: {e.caveats}</p>}
              {/* Position in the draft — computed in code after every draft /
                  refine / approval (lib/copywriting-ledger.ts). */}
              {e.placement && (
                <p className={`mt-1.5 flex items-center gap-1 text-xs ${e.placement === 'Not used in draft' ? 'text-gray-400' : 'text-gray-600'}`}>
                  <MapPin size={11} className="flex-shrink-0" />
                  {e.placement === 'Not used in draft' ? e.placement : <>In draft: {e.placement}</>}
                </p>
              )}
              <p className="mt-1.5 text-[10px] text-gray-400">Last checked {new Date(e.checked_at).toLocaleString()}</p>
              {regeneratingId === e.id && (
                <div className="mt-3">
                  <CopywritingLoader variant="research" compact />
                </div>
              )}

              {!readOnly && e.status === 'pending' && (
                <div className="mt-3 flex items-center gap-2 border-t border-[#e5e3df] pt-3">
                  <Button size="sm" onClick={() => act(e.id, 'approve')} loading={busyId === e.id}>
                    <Check size={12} className="mr-1 inline" /> Approve
                  </Button>
                  <Button size="sm" variant="secondary" onClick={() => act(e.id, 'reject')} loading={busyId === e.id}>
                    <Ban size={12} className="mr-1 inline" /> Discard
                  </Button>
                  <Button size="sm" variant="ghost" onClick={() => setRegenOpenId(regenOpenId === e.id ? null : e.id)}>
                    <RefreshCw size={12} className="mr-1 inline" /> Regenerate
                  </Button>
                </div>
              )}

              {regenOpenId === e.id && (
                <div className="mt-3 flex flex-col gap-2">
                  <Textarea label="Feedback for regeneration" rows={2} value={feedback} onChange={(ev) => setFeedback(ev.target.value)} />
                  <Button
                    size="sm"
                    className="self-start"
                    loading={busyId === e.id}
                    onClick={async () => { await act(e.id, 'regenerate', { feedback }); setFeedback(''); setRegenOpenId(null) }}
                  >
                    Regenerate
                  </Button>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
